### PR TITLE
Make it easy to try models in NetLogo Web

### PR DESCRIPTION
**Pull request by TheBizzle**
Howdy Reuven!

I felt so left out upon seeing how much fun you were having as the maintainer of the Modeling Commons recently that I decided to take it upon myself to try being the maintainer of my own local version of the Modeling Commons.

:tada: :tada: :tada:

This pull request adds a tab to model pages for running models in NetLogo Web.  This is something that's valuable to us in the CCL, especially since applets have become so unpleasant to use.  

That said, I think there are couple of things worth bringing to your attention about this PR:

First, since there are now two "Run" tabs (one for applets and one for NLW), I changed the names of the tabs to "Run as Applet" and "Run in NetLogo Web".  This causes the tab list to overflow onto a second line, which, admittedly, doesn't look nice.

mc_nlw

On the topic of applets, do you have any metrics—I'm guessing not—on how many people actually use the applets tab?  Because if no one's using the applets, we think the best thing would just be to get rid of the applets support altogether.  That would also address this verbosity problem that I introduced with the tab titles.  If people _are_ using them, though, then we probably need some other (relatively simple) solution for this UI/layout problem.

The other big thing is that I added a statement of `headers['Access-Control-Allow-Origin'] = '*'` when serving up `.nlogo` files.  Naturally, this means that any site in the universe can hit the Modeling Commons to download models.  I would expect that to not be a problem, but maybe you don't like that.  If it's the latter, then, in order for this PR to work, we would need to change it to only allow `http://netlogoweb.org`, `http://netlogo-web.org`, and the `https://` variants of both of those, as well.  Not a huge deal, but something to be aware of.

That's it from me, though.  Hopefully you think this PR is :heart:—I _did_ try to match your style as much as reasonably possible—but, of course, feel free to let me know anything here that makes you feel :fire: or :imp:, or maybe even a little :fu:, and I'll be glad to make changes as necessary.

### CODE REVIEW

**Comment by reuven** [comment]
OK, let's merge this!

**Comment by SethTisue** [comment]
> we think the best thing would just be to get rid of the applets support altogether

+1

**Comment by reuven** [comment]
@SethTisue Your wish (and mine for a long time) is my command!

Deploying applet-less Modeling Commons right now.

Truth be told, I had sort of forgotten that we still had that tab in there.  With NetLogo Web, though, now we have a better (and supported!  and safe!) way to do this.  Great news all around.

**Comment by SethTisue** [comment]
@reuven I still see the applet tab...?

**Comment by reuven** [comment]
Hmm, maybe I didn't hide it after all?  I thought that I had.  I'll double check.

Darn you for actually checking that I do what I say!

**Comment by SethTisue** [comment]
@reuven ping — applet tab is still there

**Comment by reuven** [comment]
Thanks for the reminder; I somehow forgot to push that update to production.  I just did, and --voila! -- the applets tab no longer appears to show up.  And good riddance.

**Pull request merged**
